version: '3.9'

services:
  webapi:
    image: adventureworks-webapi
    container_name: adventureworks-webapi-dev
    build:
      context: .
      dockerfile: src/AdventureWorks.WebApi/Dockerfile.debug
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=cloudiq@123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/aspnetapp.pfx
      - Redis__ConnectionString=redis:6379
      - Seq__ServerUrl=http://seq:5341
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ./aspnetapp.pfx:/aspnetapp.pfx:ro
    depends_on:
      - redis
      - seq

  redis:
    image: redis:alpine
    container_name: adventureworks-redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data

  seq:
    image: datalust/seq:latest
    container_name: adventureworks-seq
    ports:
      - "5341:80"
      - "5342:5341"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=cloudiq@123
    volumes:
      - seq-data:/data

volumes:
  redis-data:
  seq-data:
