name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore AdventureWorks.sln

      - name: Build
        run: dotnet build AdventureWorks.sln --no-restore

      - name: Test
        run: dotnet test AdventureWorks.sln --no-build --verbosity normal

      - name: Build Docker image
        run: docker build -t wellnessplan-webapi .

      # Optionally, push to Docker Hub or Azure Container Registry here

  # Add a deploy job if you want to deploy automatically after build